export const SERVICES_LOADING = 'SERVICES_LOADING';
export const ADD_SERVICES = 'ADD_SERVICES';
export const SERVICES_FAILED = 'SERVICES_FAILED';

export const ADD_REVIEWS = 'ADD_REVIEWS';
export const REVIEWS_FAILED = 'REVIEWS_FAILED';

export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';